In [14]:
import numpy as np
#1
a1 = np.array([[10, 20, 30],
               [40, 50, 60]])
a2 = np.array([1,2,3])
a3 = a1+a2
print(a3)
#####################################
a1b = np.array([[1, 2],
               [3, 4]])
a2b = np.array([10, 20]).reshape(2,1) ##I tried using matrix transpose as first intuition but it didn't work as expected so I used reshape instead
a3b=a1b*a2b
print(a3b)


[[11 22 33]
 [41 52 63]]
[[10 20]
 [60 80]]


In [44]:
#2
arr = np.arange(1, 25).reshape(2, 3, 4)
#print(arr)
#######################################
#a
print(f"a:\n {arr[1]}")
#b
print(f"b:\n {arr[:,:,-1]}")
#c
print(f"c:\n {arr[::-1,:,:]}")
#d
arr2=np.copy(arr)
arr2[arr2%2==0]=-1 #vectorized operation instead of 3 nested loops
print(f"d:\n {arr2}")    


a:
 [[13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]
b:
 [[ 4  8 12]
 [16 20 24]]
c:
 [[[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]

 [[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]]
d:
 [[[ 1 -1  3 -1]
  [ 5 -1  7 -1]
  [ 9 -1 11 -1]]

 [[13 -1 15 -1]
  [17 -1 19 -1]
  [21 -1 23 -1]]]


In [70]:
#3
#a
arr = np.array([1, 2, 3, 4, 5, 6])
arr3=np.copy(arr)
arr3a=np.array([],dtype=np.int8)
for i in range(len(arr3)):
    if arr3[i]%2>0:
       rep = np.repeat(arr3[i],2)
       arr3a = np.concatenate((arr3a,rep)) 
print(f"a: {arr3a}")  
#b
arr3b=np.array([],dtype=np.int8)
for i in range(len(arr3)):
       rep = np.repeat(arr3[i],(i+1))
       arr3b = np.concatenate((arr3b,rep))
print(f"b: {arr3b}")

  
        
        

a: [1 1 3 3 5 5]
b: [1 2 2 3 3 3 4 4 4 4 5 5 5 5 5 6 6 6 6 6 6]


In [73]:
#4
arr = np.array([10, 20, 30])
normalized = np.array((arr-np.min(arr))/(np.max(arr)-np.min(arr)), dtype= np.float32)
## in the numerator we used broadcasting to subtract the smallest value of the array from the entire array
# and in the denomenator we obtained the range of the array 
print(normalized)

[0.  0.5 1. ]


In [78]:
#bonus 
#a
arr_ij = np.empty((3,3))
for i in range(len(arr_ij)):
    for j in range(len(arr_ij)):
        arr_ij[i][j]=i*j
print(f"a: {arr_ij}")  
#b
n = int(input("Enter the size of the matrix (only square matrices)"))    
matrix = np.empty((n,n),dtype = np.float32)
for i in range(n):
    for j in range(n):
        matrix[i][j]=float(input(f"Please enter elements of the array at position:{i+1},{j+1}"))
print(f"your matrix: {matrix}")
matrix_man = np.copy(matrix)
matrix_man[np.diag_indices_from(matrix_man)] = 0
print(f"your matrix after manipulation: {matrix_man}")
 

a: [[0. 0. 0.]
 [0. 1. 2.]
 [0. 2. 4.]]
your matrix: [[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]
 [13. 14. 15. 16.]]
your matrix after manipulation: [[ 0.  2.  3.  4.]
 [ 5.  0.  7.  8.]
 [ 9. 10.  0. 12.]
 [13. 14. 15.  0.]]
